### PR TITLE
Improve config validation and some cleanup

### PR DESCRIPTION
**Pull request by raman325**
Went a little overboard here so tell me if you want me to revert any changes. The main planned change was to make the league ID a pick list since you already had all the data in the integration (see screenshot below for what it looks like). While I was doing this, I did a couple of other things which I think improve the code but again, happy to revert if you'd like:

- Switch list of lists to dictionaries which makes lookup of icon and the path data easier
- Run black formatter on all code
- Add picklist for the league, including the ability to pick specifying custom paths
- Add config validation for YAML configs to check if the league ID is valid
- Raise an error for YAML configs if league ID is XXX but sport or league path is missing
- Created constants for the sports paths which IMO just makes it less likely for someone to fat finger something
- Add missing typehints in some places (didn't cover everything)

Hope you find these changes useful!

image

### CODE REVIEW

**Comment by vasqued2** [comment]
PlatformNotReady is new to me so I want to run some tests to understand how HA handles when thrown.  

This old C programmer was able to follow the rest of the changes.  They clean things up nicely.

Is it possible and normal to run black as part of Actions?  Is that even something normal to do?  Reformatted everything a couple releases ago to get everything relatively clean but haven't kept it up over last couple releases.

Thanks

**Comment by raman325** [comment]
> PlatformNotReady is new to me so I want to run some tests to understand how HA handles when thrown.

I'm actually going to change this... when you raise `PlatformNotReady`, that tells Home Assistant to wait a bit and try again, which is not the right behavior here because the config is wrong and will never be fixed until a restart is performed. Trying to figure out an alternate solution.

**Comment by raman325** [comment]
OK so looking at the code, the proper behavior is to log an error and return without trying to set up an entity. To make it more obvious, I also added a persistent notification so the user will catch the error more quickly.

**Comment by raman325** [comment]
> Is it possible and normal to run black as part of Actions? Is that even something normal to do? Reformatted everything a couple releases ago to get everything relatively clean but haven't kept it up over last couple releases.

It's technically possible but it's a bit messy. Typically you don't want CI/Actions to modify code as part of its operation. The core repo does a check of `black` on every PR and fails the action if black would reformat the code (indicating that black needs to be run on the PR). That's probably your best option if you want to be stricter about formatting. If you'd like to enable that, I can submit a PR to add that to the actions, just let me know

**Comment by vasqued2** [comment]
I really like the approach using the notification.  

I won't have a chance to run it locally until this weekend but it looks like it's going to produce the same message if the yaml has an invalid league_id or has league_id = XXX and is missing one of the paths.  Maybe I'm just missing something since I have not run it yet to see how it functions.

No need to do anything with black.  Thanks for the offer.

**Comment by raman325** [comment]
if the league ID is invalid, the config validation will fail and the user will get a different error in the logs saying that their config needs to be updated. That is something that HA will handle because the config schema (https://github.com/vasqued2/ha-teamtracker/pull/92/files#diff-9da12d3edf8986ff8fecd35813fcfdd0bc251f120f1230dc239e474576fb00c1R42-R50) requires that the league ID be in the list that's provided. This does make me realize that this will fail if the user provides a correct league ID but in lowercase. I will fix that shortly

**Comment by vasqued2** [comment]
I finally had a chance to download and play with it.  I really like these changes and will pull them in.  I learned a lot from them. 
 I'd like to make the following adjustments before I pull them in.  I can make them or you can.

- Because many people set up multiple sensors for different teams/sports, I would like to prefix the error logs and notifications with the sensor name to help them know which sensor is causing the problem.
- Rather than enforcing valid league names in YAML via the schema immediately, I'd like to split this into two releases.  The first release should include all this functionality except the schema enforcement, and instead, kick out a warning in the logs saying that they need to fix their YAML before the next release.  Although unlikely, it is possible someone has a bad sensor config in their YAML and I don't want an upgrade to suddenly fail a configuration check without a warning first.  The follow-up release can then enforce the valid league names after they had a chance to act on the warning.

I also have a question on the error message with an invalid league ID is specified in the YAML and I'll include it in the next comment.

**Comment by vasqued2** [comment]
I noticed the error in the Configuration Check when there is a bad league_id says "(See ?, line ?)" at the end.  I'm assuming this is supposed to be the file name and line number instead of ? but have no idea how or even if they can be populated.

image

**Comment by raman325** [comment]
Glad this was helpful! 

> * Because many people set up multiple sensors for different teams/sports, I would like to prefix the error logs and notifications with the sensor name to help them know which sensor is causing the problem.

Sure I can add that

> * Rather than enforcing valid league names in YAML via the schema immediately, I'd like to split this into two releases.  The first release should include all this functionality except the schema enforcement, and instead, kick out a warning in the logs saying that they need to fix their YAML before the next release.  Although unlikely, it is possible someone has a bad sensor config in their YAML and I don't want an upgrade to suddenly fail a configuration check without a warning first.  The follow-up release can then enforce the valid league names after they had a chance to act on the warning.

Sure we can do this, but I don't think there's harm in making this a configuration check failure because as of now, if the user has a bad sensor config, the sensor will not set up properly and they will get an error but it will be less clear on how to fix it vs the configuration check failure. Basically we're just shifting how the error is communicated, it doesn't change anything for working sensors etc. Do you still want to split this up? Happy to make this change, just want to make sure you have full context before I do.

> I also have a question on the error message with an invalid league ID is specified in the YAML and I'll include it in the next comment.

Home Assistant provides this error so there's nothing we can do to address those question marks. I have noticed that issue though elsewhere as well, maybe this is something I need to look into in the core code at some point.

**Comment by vasqued2** [comment]
It's the configuration check w/ the ?'s that makes me want to split it out.  

When I ran the check I saw the error, it prevented me from restarting w/ a config that had previously worked.  I knew what was going on and still my first thought was that I was going to have to have to use trial and error to delete my sensors until I found my troublemaker.  Once I got in I realized I had previously set up a sensor to test this specific error case and deleted it, but it could be disorienting for someone else who set something up wrong, didn't delete it, and set up a second sensor correctly.  Theoretically, they could also use a league ID like ZZZ or something else to set up a Custom API and it would work until this check flagged it.  I understand both are unlikely but I'd like to give a warning just in case.

As an added note, I did notice that if I force a reboot even w/ the invalid league ID's, the error in the log correctly lists the file and line number.  If this was working in the config check, I'd feel better about not splitting it out.  It's because it's not that I want to split it out.

**Comment by raman325** [comment]
Got it ok 👌

**Comment by vasqued2** [comment]
Thanks for your help.  I'll pull all these in as soon as I get a chance.

**Pull request merged**
